#!/usr/bin/env bash
./gradlew clean
./gradlew :oklog-shared:publishBintrayPublicationToMavenLocal
./gradlew :oklog-core:publishBintrayPublicationToMavenLocal
./gradlew :oklog-java:publishBintrayPublicationToMavenLocal
./gradlew :oklog3-java:publishBintrayPublicationToMavenLocal
./gradlew :oklog-core-android:install
./gradlew :oklog:install
./gradlew :oklog3:install
