#!/bin/bash

if [ "$TEST_SUITE" = "integration" ]
then

    # Create emulator
    echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI -c 100M
    emulator -avd test -no-skin -no-audio -no-window &

fi
